cp,nump,vup=input().split()
cp2,nump2,vup2=input().split()
cp=int(cp)
nump=int(nump)
vup=float(vup)
cp2=int(cp2)
nump2=int(nump2)
vup2=float(vup2)
sol=(nump*vup)+(nump2*vup2)
print("VALOR A PAGAR: R$ {:.2f}".format(sol))